### ISSUE TITLE
ProgressBar in Teil_III/11_Kochrezepte/11-11_Stapelverarbeitung.jsx dosn't show up

### ISSUE THREAD

**Issue by Vispercept** [grefel/indesignjs#2]
Unfortunately the progressbar doesn't show up. Seems like the `enableRedraw` and/or `userInteractionLevel` settings doesn't work. If i put in an alert in the loop over the files, the bar shows up...

**Comment by grefel** [comment]
Which version + platform do you use? With CC 2015 and CS6 on windows everything works as expected.

**Comment by Vispercept** [comment]
Hey. I'm working on InDesign CC 2015.3 Release - Build 11.3.0.34 on a MacBook :-)
